ChurchApps/ChumsApp

- src/helpers/ImportHelper.ts
- src/settings/ExportPage.tsx
- src/settings/ImportPage.tsx
- src/settings/components/ImportPreview.tsx
- src/settings/components/ImportStatus.tsx
exporting forms is still in progress
> fix: import/export

- cypress/integration/Attendance.spec.js
- cypress/integration/Groups.spec.js
- cypress/integration/Person.spec.js
- cypress/support/apiHelpers.js
Make appropriate API changes so tests start running properly again
> fix: Cypress tests

- src/Login.tsx
- src/components/Header.tsx
- src/helpers/PersonHelper.ts
App failed to log user in incase user deletes the person which we provide in the very beginning.
> fix app from crashing when user deletes a person

- src/people/components/PersonEdit.tsx
Resolves  https://github.com/LiveChurchSolutions/ChumsApp/issues/21.
I prefer this implementation instead of importing massive libraries only to format the phone number. If we plan on using this formatting in rest of the family apps, we'll just move this to appBase under helper functions.
> format phone number as user types

- src/people/components/PersonView.tsx
https://github.com/LiveChurchSolutions/ChumsApp/issues/19
> Anniversary date issue

- src/people/components/PersonEdit.tsx
https://github.com/LiveChurchSolutions/ChumsApp/issues/31
> Change layout of edit person page

- dotenv.sample.txt
- src/Forgot.tsx
- src/attendance/AttendancePage.tsx
- src/donations/DonationsPage.tsx
- src/donations/FundPage.tsx
- src/donations/components/Donations.tsx
- src/donations/components/Funds.tsx
- src/forms/FormPage.tsx
- src/forms/FormsPage.tsx
- src/forms/components/FormQuestionEdit.tsx
- src/groups/GroupsPage.tsx
- src/groups/components/GroupMembers.tsx
- src/groups/components/MembersAdd.tsx
- src/helpers/EnvironmentHelper.ts
- src/people/PeoplePage.tsx
- src/people/components/Groups.tsx
- src/people/components/PersonAttendance.tsx
- src/people/components/PersonDonations.tsx
- src/people/components/PersonView.tsx
a part of this https://github.com/LiveChurchSolutions/ChumsApp/issues/2
> In general fixes

- src/people/components/BankForm.tsx
- src/people/components/CardForm.tsx
Unused set state functions causing the deploy to fail.
> Remove unused set state functions

- src/components/Notes.tsx
- src/donations/components/FundEdit.tsx
- src/forms/components/FormEdit.tsx
- src/forms/components/FormQuestionEdit.tsx
- src/groups/components/GroupAdd.tsx
- src/helpers/index.ts
- src/people/components/PersonEdit.tsx
https://github.com/LiveChurchSolutions/AccountsApp/issues/32
> validate inputs

- src/components/Note.tsx
- src/components/Notes.tsx
https://github.com/LiveChurchSolutions/ChumsApp/issues/2
> fix bugs from notes section

- public/css/all.css
- src/components/AssociatedForms.tsx
- src/components/FormSubmission.tsx
- src/components/FormSubmissionEdit.tsx
- src/components/Header.tsx
- src/people/PersonPage.tsx
- src/people/components/Person.tsx
- src/people/components/PersonEdit.tsx
- src/people/components/PersonView.tsx
Resolves https://github.com/LiveChurchSolutions/ChumsApp/issues/63
> Save forms for person

- src/attendance/AttendancePage.tsx
Resolves https://github.com/LiveChurchSolutions/ChumsApp/issues/59
> Sort table on attendance page alphabetically

- src/groups/GroupsPage.tsx
- src/groups/components/GroupMembers.tsx
- src/groups/components/GroupSessions.tsx
- src/groups/components/MembersAdd.tsx
- src/helpers/PersonHelper.ts
- src/people/PersonPage.tsx
- src/people/components/ImageEditor.tsx
- src/people/components/Person.tsx
- src/people/components/PersonEdit.tsx
- src/people/components/PersonView.tsx
Resolves https://github.com/LiveChurchSolutions/ChumsApp/issues/86
> fix: person image can be deleted

- src/Login.tsx
https://github.com/LiveChurchSolutions/AccessApi/issues/48
> refactor(login): update the api for fetching person record

- src/people/components/BankForm.tsx
- src/people/components/CardForm.tsx
- src/people/components/PersonDonations.tsx
- src/people/components/PersonPaymentMethods.tsx
- Adds error messages/handling to the card form
- Adds a person's name when creating a new Stripe customer
- Reloads donation data on payment method updates
- Adds notes to new recurring donations
> Donation fixes

- src/components/NavItems.tsx
- src/donations/components/DonationEvents.tsx
- Tweak the donation error log design
- Add error icon to navbar when an unresolved donation error exists.
> Update donation event error log

- public/css/all.css
- src/components/Note.tsx
Fixes https://github.com/LiveChurchSolutions/ChumsApp/issues/82
> fix(notes): instead of br tag a new line should be shown

- src/components/Header.tsx
- src/components/NavItems.tsx
Fixes https://github.com/LiveChurchSolutions/ChumsApp/issues/91
> fix: navbar dropdown menu

- src/donations/DonationsPage.tsx
- src/settings/components/ImportPreview.tsx
This fixes a bug where the date was displaying one day earlier than what was being saved. https://github.com/LiveChurchSolutions/ChumsApp/issues/120
> Date helper updates

- src/attendance/components/CampusEdit.tsx
- src/attendance/components/ServiceEdit.tsx
- src/attendance/components/ServiceTimeEdit.tsx
resolves https://github.com/LiveChurchSolutions/ChumsApp/issues/133
> don't show delete buttons when creating a new record

- src/Login.tsx
- src/components/Header.tsx
resolves https://github.com/LiveChurchSolutions/AccessApi/issues/83
> show an access error for claimed churches

- src/helpers/UserHelper.ts
- src/settings/SettingsPage.tsx
resolves https://github.com/LiveChurchSolutions/ChumsApp/issues/140
> fix manage church button

- src/Login.tsx
https://github.com/LiveChurchSolutions/AccessApi/issues/76
> remove /churchapps/register call

- src/people/PersonPage.tsx
- src/people/components/Person.tsx
- src/people/components/PersonEdit.tsx
resolves https://github.com/LiveChurchSolutions/ChumsApp/issues/147. 
The code may look a bit hacky but it's the easiest way imo.
> keep edited person record on changing profile image

- src/components/index.ts
- src/helpers/UploadHelper.ts
- src/settings/ImportPage.tsx
- src/settings/components/ImportStatus.tsx
This fixes the issue where the groups are not loaded in properly with the csv upload.
> Trim headers when reading csv so they are not strings

- src/people/components/PersonEdit.tsx
resolves https://github.com/LiveChurchSolutions/ChumsApp/issues/198
> fix: allow a user to change address of whole household

- src/donations/DonationBatchPage.tsx
- src/donations/DonationsPage.tsx
resolves https://github.com/LiveChurchSolutions/ChumsApp/issues/187
> fix: use batch name instead of ids

- src/profile/ProfilePage.tsx
Frontend changes for https://github.com/LiveChurchSolutions/ChurchAppsSupport/issues/86
> add delete account

- package-lock.json
- src/tasks/components/NewTask.tsx
I made it date time, let's merge this to at least get the crashing to stop and then I will keep working on task features.
> issue resolved tasks working.

- src/people/PeoplePage.tsx
- src/people/components/PersonEdit.tsx
You will need to add a new column to the membership database in the people table "nametagNotes"
> Issue 114 Name Tag Notes

- src/helpers/ChumsPersonHelper.ts
- src/people/components/PeopleSearchResults.tsx
Fixes https://github.com/LiveChurchSolutions/ChurchAppsSupport/issues/116. The date was being parsed into a date with no timezone offset but formatted as a date with a timezone offset. Now the date is formatted as a date without a timezone offset, which fixes the issue.
> Fixed date display issue

- src/tasks/automations/AutomationsPage.tsx
- src/tasks/automations/components/AutomationDetails.tsx
- src/tasks/automations/components/AutomationEdit.tsx
resolved: https://github.com/LiveChurchSolutions/ChurchAppsSupport/issues/148
> feat: allow to delete automations

- src/forms/components/FormMembers.tsx
resolved: https://github.com/LiveChurchSolutions/ChurchAppsSupport/issues/152
> feat: add emailAccess option to form members

- src/people/components/PeopleColumns.tsx
resolved: https://github.com/LiveChurchSolutions/ChurchAppsSupport/issues/150
> fix: add checkboxes instead of icon for people search

- src/settings/components/GivingSettingsEdit.tsx
Added a new option in the admin settings that will automatically apply the transaction fees when it's 'On'.
> feat: add transaction fee option

- src/donations/components/DonationEdit.tsx
https://github.com/ChurchApps/ChurchAppsSupport/issues/234
> switch default payment method for donations

- src/donations/components/Donations.tsx
https://github.com/ChurchApps/ChurchAppsSupport/issues/233
> show total amount for individual batch

- src/donations/DonationsPage.tsx
- src/people/components/PeopleSearchResults.tsx
https://github.com/ChurchApps/ChurchAppsSupport/issues/230
> improve: add sorting to donation batches

- src/components/AssociatedForms.tsx
- src/forms/components/Tabs.tsx
https://github.com/ChurchApps/ChurchAppsSupport/issues/236
> add form submissions tab to associated forms

- src/people/components/EditCondition.tsx
- src/people/components/PeopleSearch.tsx
https://github.com/ChurchApps/ChurchAppsSupport/issues/17
> feat: add donation filter to advanced search

- package-lock.json
- package.json
- src/people/components/PersonEdit.tsx
- src/people/components/PersonView.tsx
https://github.com/ChurchApps/ChurchAppsSupport/issues/249
> improve: international support to phone numbers

- src/donations/DonationsPage.tsx
https://github.com/ChurchApps/ChurchAppsSupport/issues/205
> fix: batch dates being 1 day off

- src/people/components/PeopleColumns.tsx
- src/people/components/PeopleSearchResults.tsx
https://github.com/ChurchApps/ChurchAppsSupport/issues/264
> improve: person search filter

- package-lock.json
- package.json
- src/forms/components/FormQuestionEdit.tsx
- src/forms/components/FormSubmissions.tsx
https://github.com/ChurchApps/ChurchAppsSupport/issues/261
> feat: add checkbox option in forms

- src/people/PeoplePage.tsx
- src/people/components/PeopleSearchResults.tsx
https://github.com/ChurchApps/ChurchAppsSupport/issues/260
> feat: add delete option to filter

- src/people/components/PeopleColumns.tsx
- src/people/components/PeopleSearchResults.tsx
https://github.com/ChurchApps/ChurchAppsSupport/issues/269
> improve: add optional fields to people filter and change UI

- src/plans/components/PlanValidation.tsx
https://github.com/ChurchApps/ChurchAppsSupport/issues/263
> improve: check other plans when validating

- src/people/PeoplePage.tsx
https://github.com/ChurchApps/ChurchAppsSupport/issues/278
> improve: save people filters to sessionStorage

- src/groups/components/GroupMembers.tsx
https://github.com/ChurchApps/ChurchAppsSupport/issues/280
> feat: message group members

- README.md
- Fix minor grammatical error
- Emojify sub-headings
> Minor Readme updates

- public/locales/en.json
- src/groups/components/GroupMembers.tsx
https://github.com/ChurchApps/ChurchAppsSupport/issues/302
> feat: add templates to group message

- src/settings/RolePage.tsx
- src/settings/components/RoleMembers.tsx
resolved: https://github.com/ChurchApps/ChurchAppsSupport/issues/338
> improve: unable to delete last domain admin

- src/groups/components/GroupMembers.tsx
resolved: https://github.com/ChurchApps/ChurchAppsSupport/issues/349
> fix: group members to leader duplicates

- src/tasks/components/NewTask.tsx
https://github.com/ChurchApps/ChurchAppsSupport/issues/343
> improve: send task assigning notification

- package-lock.json
- package.json
- public/locales/en.json
- src/donations/components/FundEdit.tsx
- src/donations/components/Funds.tsx
https://github.com/ChurchApps/ChurchAppsSupport/issues/303
> add: tax deductible to funds

- src/tasks/components/RequestedChanges.tsx
https://github.com/ChurchApps/ChurchAppsSupport/issues/419
> improve: add family member to modify profile

- package-lock.json
- package.json
- public/locales/en.json
- src/groups/components/GroupDetails.tsx
- src/groups/components/GroupDetailsEdit.tsx
https://github.com/ChurchApps/ChurchAppsSupport/issues/270
> add: print nametag field to groups

- public/locales/en.json
- src/settings/components/ChurchSettingsEdit.tsx
- src/settings/components/VisibilityPrefSettingsEdit.tsx
https://github.com/ChurchApps/ChurchAppsSupport/issues/443
> add: visibility pref to church setting

- package-lock.json
- package.json
- src/forms/components/FormEdit.tsx
- tsconfig.json
The admin/leader side, edited so they can have a custom thank you message at the end of forms for B1.
> thanksMessage

- src/groups/components/GroupSessions.tsx
https://github.com/ChurchApps/ChurchAppsSupport/issues/505
> improve: session download

- package-lock.json
- package.json
- src/Authenticated.tsx
- src/donations/PrintDonationPage.tsx
https://github.com/ChurchApps/ChurchAppsSupport/issues/493
> add: print donations option to people

- public/locales/en.json
- src/settings/components/FeeOptionsSettingsEdit.tsx
- src/settings/components/GivingSettingsEdit.tsx
https://github.com/ChurchApps/ChurchAppsSupport/issues/433
> add: credit card/ach fees options

- src/groups/components/GroupDetailsEdit.tsx
https://github.com/ChurchApps/ChurchAppsSupport/issues/540
> improve: change group image ratio to 16:9

- src/plans/components/PlanValidation.tsx
https://github.com/ChurchApps/ChurchAppsSupport/issues/527
> add: link field to /notifications/create

- public/locales/en.json
- src/serverAdmin/AdminPage.tsx
- src/serverAdmin/components/TranslationTab.tsx
Added tab to server admin pages allowing data on bible translation lookups.
> TranslationLookupTab
